services:
  - type: web
    name: dealdisha-web
    env: node
    region: oregon # You can change this to a region closer to you (e.g., frankfurt, ohio, singapore)
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run start
    envVars:
      - key: DATABASE_URL
        value: file:/data/prod.db
      - key: NODE_ENV
        value: production
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
